
const nodemailer = require("nodemailer");

let transporter = null;

async function getTestTransporter() {
  if (transporter) {
    return transporter;
  }

  const testAccount = await nodemailer.createTestAccount();

  console.log("Ethereal test account created:");
  console.log("Email:", testAccount.user);

  transporter = nodemailer.createTransport({
    host: "smtp.ethereal.email",
    port: 587,
    secure: false,
    auth: {
      user: testAccount.user,
      pass: testAccount.pass,
    },
  });

  return transporter;
}

async function sendInterviewEmail(candidateEmail, interviewUrl) {
  if (!candidateEmail) {
    throw new Error("Candidate email is missing.");
  }

  const mailer = await getTestTransporter();

  const info = await mailer.sendMail({
    from: '"AI Resume Analyzer" <test@ethereal.email>',
    to: candidateEmail,
    subject: "Interview Invitation - AI Resume Analyzer",
    text: `Hello,

You have been invited to an interview.

Please use this link:
${interviewUrl}

This is a test email generated by AI Resume Analyzer.`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
        <h2>Interview Invitation</h2>
        <p>Hello,</p>
        <p>You have been invited to an interview.</p>
        <p>
          <a href="${interviewUrl}"
             style="display:inline-block;padding:12px 20px;background:#2563eb;color:white;text-decoration:none;border-radius:6px;">
            Start Interview
          </a>
        </p>
        <p>This is a test email generated by AI Resume Analyzer.</p>
      </div>
    `,
  });

  const previewUrl = nodemailer.getTestMessageUrl(info);

  console.log("Email sent to Ethereal:", candidateEmail);
  console.log("Preview URL:", previewUrl);

  return {
    messageId: info.messageId,
    previewUrl,
  };
}

module.exports = {
  sendInterviewEmail,
};